Check for empty filters
hkulekci/qdrant-php pull request #25
Opened 2023-07-05 05:35 UTC by gregpriday

Passing an empty array causes an error with the Qdrant server, so this is just one last sanity check.

It's foreseeable that a developer might construct a `Filter` over a series of steps, and in the end, have an empty Filter object.  You can see the test I added to see what this PR solves.

2023-07-05 15:15 UTC, hkulekci requested changes

2023-07-05 15:15 UTC, hkulekci commented on src/Models/Request/RecommendRequest.php
> +        if ($this->filter !== null && $this->filter->toArray()) {
Same here!

2023-07-06 03:06 UTC, gregpriday commented on src/Models/Request/SearchRequest.php
> +        if ($this->filter !== null && $this->filter->toArray()) {
In my opinion, an exception would be too aggressive. In this case, an empty array isn't technically invalid, so throwing an InvalidArgumentException might not make sense.

Another option would be to add a dedicated `isEmpty` function or for `Filter` to implement `Countable`, and have `function count` return the number of filters, which makes sense. That way we could just say `if(!empty($this->filter))...` (I haven't tested if this works though). If that doesn't work, then the condition could just be `if($this->filter !== null && $this->filter->count())`.

2023-07-06 06:45 UTC, hkulekci commented on src/Models/Request/SearchRequest.php
> +        if ($this->filter !== null && $this->filter->toArray()) {
Okay great. Understood. So, maybe we can continue as is for now. The other solutions will be nearly same what we have now.

2023-07-06 06:46 UTC, hkulekci approved these changes

2023-07-06 06:46 UTC, merged